<?xml version="1.0"?>
<!--

$Id: header.jspf 2712 2008-03-10 17:01:01Z davemckain $

Stylesheet to soup up the raw output from the SnuggleTeX
process to make a nice web page.

This adds in the rest of the <head/> stuff, standard headers & footers
and the navigation menu.

Relative links are fixed up so they are relative to the supplied
context-path.

Copyright (c) 2008 University of Edinburgh.
All Rights Reserved

-->
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:m="http://www.w3.org/1998/Math/MathML"
  xmlns:s="http://www.ph.ed.ac.uk/snuggletex"
  xmlns="http://www.w3.org/1999/xhtml"
  xpath-default-namespace="http://www.w3.org/1999/xhtml"
  exclude-result-prefixes="m s">

  <xsl:output method="xhtml"/>

  <!-- Extract page title as first <h2/> heading -->
  <xsl:variable name="title" select="/html/body/h2[1]/text()"/>

  <!-- Need to pass webapp context path so as to locate images and stuff -->
  <xsl:param name="context-path"/>

  <xsl:template match="html">
    <html xml:lang="en" lang="en">
      <xsl:copy-of select="@*"/>
      <xsl:apply-templates/>
    </html>
  </xsl:template>

  <xsl:template match="head">
    <head>
      <title>SnuggleTeX - <xsl:value-of select="$title"/></title>
      <!-- Copy the default <head/> stuff generated by the serializer -->
      <xsl:apply-templates/>
      <meta name="description" content="SnuggleTeX Documentation" />
      <meta name="author" content="David McKain" />
      <meta name="publisher" content="The University of Edinburgh" />
      <link rel="stylesheet" href="{$context-path}/includes/core.css" />
      <link rel="stylesheet" href="{$context-path}/includes/website.css" />
      <link rel="stylesheet" href="{$context-path}/includes/snuggletex.css" />
    </head>
  </xsl:template>

  <xsl:template match="body">
    <body id="{s:pageId[1]}">
      <table width="100%" border="0" cellspacing="0" cellpadding="0" id="header">
        <tr>
          <td width="84" align="left" valign="top">
            <a href="http://www.ed.ac.uk" class="headertext"><img
              src="{$context-path}/includes/uoe_logo.jpg"
              alt="The University of Edinburgh" id="logo" name="logo"
              width="84" height="84" border="0" /></a>
          </td>
          <td align="left">
            <h3>THE UNIVERSITY of EDINBURGH</h3>
            <h1>SCHOOL OF PHYSICS AND ASTRONOMY</h1>
          </td>
          <td align="right">
            <table border="0" cellpadding="0" cellspacing="0" style="margin-right:20px;">
              <tr>
                <td>
                  <a href="http://www.ed.ac.uk" class="headertext"><img
                    src="{$context-path}/includes/arrow.gif"
                    width="16" height="11" border="0"
                    alt="" />University&#160;Homepage</a>
                  <br />
                  <a href="http://www.ph.ed.ac.uk" class="headertext"><img
                    src="{$context-path}/includes/arrow.gif"
                    width="16" height="11" border="0"
                    alt="" />School of Physics and Astronomy Homepage</a>
                  <br />
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <h1 id="location">
        <a href="{$context-path}">SnuggleTeX (v1.0.0-beta5)</a>
      </h1>
      <div id="content">
        <div id="skipnavigation">
          <a href="#maincontent">Skip Navigation</a>
        </div>
        <div id="navigation">
          <div id="navinner">
            <!-- Standard Navigation -->
            <h2>About SnuggleTeX</h2>
            <ul>
              <li><a class="overview" href="{$context-path}/docs/overview.xml">Overview</a></li>
              <li><a class="features" href="{$context-path}/docs/features.xml">Features</a></li>
              <li><a class="usecases" href="{$context-path}/docs/use-cases.xml">Use Cases</a></li>
              <li><a class="releasenotes" href="{$context-path}/docs/release-notes.xml">Release Notes</a></li>
              <li><a href="http://sourceforge.net/project/showfiles.php?group_id=221375">Download from SourceForge.net</a></li>
            </ul>

            <h2>User Guide</h2>
            <ul>
              <li><a class="requirements" href="{$context-path}/docs/requirements.xml">Software Requirements</a></li>
              <li><a class="gettingstarted" href="{$context-path}/docs/getting-started.xml">Getting Started</a></li>
              <li><a class="usageoverview" href="{$context-path}/docs/usage-overview.xml">Usage Overview</a></li>
              <li><a class="minexample" href="{$context-path}/docs/minimal-example.xml">Minimal Example</a></li>
              <li><a class="inputs" href="{$context-path}/docs/inputs.xml">Inputs</a></li>
              <li><a class="outputs" href="{$context-path}/docs/outputs.xml">Outputs</a></li>
              <li><a class="errors" href="{$context-path}/docs/error-reporting.xml">Error Reporting</a></li>
              <li><a class="configuration" href="{$context-path}/docs/configuration.xml">Configuration</a></li>
              <li><a class="projects" href="{$context-path}/javadoc/">API Documentation</a></li>
            </ul>

            <h2>Demos and Samples</h2>
            <ul>
              <li><a class="samples" href="{$context-path}/docs/latex-samples.xml">LaTeX Samples</a></li>
              <li><a class="tryout" href="{$context-path}/tryout.xml">Try Out</a></li>
            </ul>

            <h2>External Links</h2>
            <ul>
              <li><a href="http://sourceforge.net/projects/snuggletex/">SnuggleTeX on SourceForge.net</a></li>
              <li><a href="https://www.wiki.ed.ac.uk/display/Physics/SnuggleTeX">SnuggleTeX Wiki</a></li>
            </ul>
          </div>
        </div>
        <div id="maincontent">
          <div id="maininner">
            <!-- Generate page content -->
            <xsl:apply-templates/>
          </div>
        </div>
      </div>
      <div id="copyright">
        <p>
          SnuggleTeX Release 1.0.0-beta5 &#x2014;
          <a href="{$context-path}/docs/release-notes.xml">Release Notes</a>
          <br />
          Copyright &#xa9; 2008
          <a href="http://www.ph.ed.ac.uk">The School of Physics and Astronomy</a>,
          <a href="http://www.ed.ac.uk">The University of Edinburgh</a>.
          <br />
          For more information, contact
          <a href="http://www.ph.ed.ac.uk/elearning/contacts/#dmckain">David McKain</a>.
        </p>
        <p>
          The University of Edinburgh is a charitable body, registered in Scotland,
          with registration number SC005336.
        </p>
      </div>
    </body>
  </xsl:template>

  <!-- Copy all other HTML and MathML as-is -->
  <xsl:template match="*">
    <xsl:copy>
      <xsl:copy-of select="@*"/>
      <xsl:apply-templates/>
    </xsl:copy>
  </xsl:template>

  <!-- Keep any PI's (e.g. for MathPlayer) -->
  <xsl:template match="processing-instruction()">
    <xsl:copy-of select="."/>
  </xsl:template>

  <!-- Leave out SnuggleTeX metadata -->
  <xsl:template match="s:*"/>

</xsl:stylesheet>
