/* $Id$
 *
 * Copyright 2008 University of Edinburgh.
 * All Rights Reserved
 */
package uk.ac.ed.ph.snuggletex;

import uk.ac.ed.ph.snuggletex.definitions.Globals;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Properties;
import java.util.Map.Entry;

/**
 * FIXME: Document this type!
 *
 * @author  David McKain
 * @version $Revision$
 */
public class CSSUtilities {
    
    public static void writeStylesheet(SnuggleTeXConfiguration configuration, OutputStream cssOutputStream) {
        /* First of all, see if custom CSS has been specified */
        Properties cssProperties = configuration.getInlineCSSProperties();
        if (cssProperties==null) {
            cssProperties = readBuiltinInlineCSSProperties();
        }
        writeStylesheet(cssProperties, cssOutputStream);
    }
    
    public static void writeDefaultStylesheet(OutputStream cssOutputStream) {
        writeStylesheet(readBuiltinInlineCSSProperties(), cssOutputStream);
    }
    
    public static void writeStylesheet(Properties cssProperties, OutputStream cssOutputStream) {
        PrintWriter writer = new PrintWriter(new BufferedOutputStream(cssOutputStream));
        writer.println("/* SnuggleTeX CSS File (autogenerated) */");
        for (Entry<Object, Object> entry : cssProperties.entrySet()) {
            writer.print("\n");
            writer.print(entry.getKey()); /* element.class */
            writer.print(" {\n  "); /* open '{' */
            writer.print(entry.getValue()); /* CSS declaration (not worth putting on multiple lines) */
            writer.print("\n}\n");
        }
        writer.close();
    }
    
    /**
     * Reads in the default CSS Properties file, which is packaged within SnuggleTeX itself.
     */
    public static Properties readBuiltinInlineCSSProperties() {
        Properties builtinInlineCSSProperties = new Properties();
        try {
            builtinInlineCSSProperties.load(CSSUtilities.class.getClassLoader().getResourceAsStream(Globals.CSS_PROPERTIES_NAME));
        }
        catch (IOException e) {
            throw new SnuggleLogicException("Could not load CSS properties file via ClassLoader " + Globals.CSS_PROPERTIES_NAME);
        }
        return builtinInlineCSSProperties;
    }
    
    /**
     * Main method is used by the build process to write out the default CSS stylesheet.
     * 
     * @param args Array containing 1 argument: the File that the default CSS should be written to.
     * 
     * @throws FileNotFoundException 
     */
    public static void main(String[] args) throws IOException {
        if (args.length!=1) {
            System.err.println("Usage: specify a File that the default SnuggleTeX CSS will be written to");
        }
        writeDefaultStylesheet(new FileOutputStream(new File(args[0])));
    }
}
